print("=================================")
print("Data Diri")
print("Nama\t: Nizar Kurnia Alfaizi")
print("Nim\t: 0110223107")
print("Kelas\t: TI03")
print("Alamat\t: Bojonggede")
print("=================================")